### ISSUE TITLE
UpgradeRequestDestination: The destination reported an error when copying the upgraded request body.

### ISSUE THREAD

**Issue by p0w1nd-cyber8** [PlayFab/MultiplayerServerSecureWebsocket#3]
Sometimes I encounter this error:
`UpgradeRequestDestination: The destination reported an error when copying the upgraded request body.`

which causes the WebGL game client cannot connect to PlayFab multiplayer server.

It's random and I don't know a reproducible rule yet.

I know this error is from YARP: https://github.com/microsoft/reverse-proxy/blob/main/src/ReverseProxy/Forwarder/HttpForwarder.cs

but I have no idea as I have no experience with proxy server / YARP.

Can someone help explain what this message is about, and what I should look into to debug it? Thanks.

![image (2)](https://user-images.githubusercontent.com/97083071/161275453-904d6a4b-33b8-4b38-8a16-9215593f5f1c.png)

**Comment by AustinBrunkhorst** [comment]
I'm sorry to hear about the issues you're experiencing. 

1. How frequently do you encounter this error?
2. Are you using a WebSocket library on your game server?

The error seems to indicate the socket connection is closed while the reverse proxy is attempting to write to it.

**Comment by p0w1nd** [comment]
BTW, on PlayFab dashboard, Multiplayer -> Servers -> New Build
I see this section:

<img width="796" alt="Screen Shot 2022-04-05 at 17 11 31" src="https://user-images.githubusercontent.com/14937764/161731843-c5544e2b-22f5-40df-acd1-99e453c652f9.png">

I'm wondering if it relates to the issue that this repo is solving. I mean, if we can upload this certificate then we won't need to go through this Proxy Server route?

**Comment by AustinBrunkhorst** [comment]
> I see this log quite often. And it seems when this happens the server will be "dead". I have to restart the server.

What is the typical lifetime (duration in the Active state) for your game servers? I'm wondering if this issue is caused by the reverse proxy not gracefully handling closed WebSocket connections which leads to the dead state.

On https://developer.playfab.com you can monitor your servers in real time on the **Servers** tab of your build.

![image](https://user-images.githubusercontent.com/499591/161834736-a5f05cbc-67a7-410a-a76f-08fcf25bf47d.png)


We haven't tested the project in this repository with Unity + Mirror Networking. Let me setup a test project and try and reproduce these failures.

**Comment by AustinBrunkhorst** [comment]
> BTW, on PlayFab dashboard, Multiplayer -> Servers -> New Build I see this section:
> 
> <img alt="Screen Shot 2022-04-05 at 17 11 31" width="796" src="https://user-images.githubusercontent.com/14937764/161731843-c5544e2b-22f5-40df-acd1-99e453c652f9.png">
> 
> I'm wondering if it relates to the issue that this repo is solving. I mean, if we can upload this certificate then we won't need to go through this Proxy Server route?

Unfortunately Azure cannot issue certificates for game server public FQDN i.e. `*.cloudapp.azure.com`, so the build certificates functionality would not work for SSL certs.

**Comment by p0w1nd** [comment]
We ended up using Nginx for the reverse proxy solution. Seems it's been working well till now.

**Comment by AustinBrunkhorst** [comment]
Thanks for the update @p0w1nd. Are you able to share some of the details of your NGINX implementation? I'm curious how you resolve a server session's FQDN within NGINX. 

We can update this repository to offer NGINX as an alternate to YARP if it's been working well for you.

**Comment by p0w1nd** [comment]
Well, actually we do FQDN resolution in client code 🙃, then post this URL (in the form of `wss://domain/server_address/ip`) to NGINX - which in turn proxy to `server_address:ip`

I know this can have a security risk but we're stuck with this _MultiplayerServerSecureWebsocket_ so we have no choice at the moment.

**Comment by AustinBrunkhorst** [comment]
> Well, actually we do FQDN resolution in client code 🙃, then post this URL (in the form of `wss://domain/server_address/ip`) to NGINX - which in turn proxy to `server_address:ip`
> 
> I know this can have a security risk but we're stuck with this _MultiplayerServerSecureWebsocket_ solution so we have no choice at the moment.

Would you be interested in joining a call with our team to troubleshoot the issues you're stuck with in MultiplayerServerSecureWebsocket? We're hoping to reach a reliable and secure solution for you as soon as we can. Feel free to reach out to **austin ( at ) xbox [ dot ] com** and we can coordinate from there.

**Comment by AustinBrunkhorst** [comment]
Hi @p0w1nd-cyber8 and @p0w1nd, just wanted to follow up on this since we haven't heard back.
